### PR TITLE
More deleting

### PR DESCRIPTION
**Pull request by liamhuber**
Just my first foray into ironflow:
- Fix TODO where deleting a node leaves the connections lying around
- Remove deleted elements from underlying ryven flow
- Add a GUI button for deleting selected objects

EDIT: This (and other drafts) are ready for review, but with the "stacked PR" workflow, review goes from the ground up but merging goes from the top down -- so this will be the last PR to actually merge.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@liamhuber I have some ideas regarding iron flow, is your MPIE email still valid?

**Comment by liamhuber** [comment]
I'm using [stacked PRs](https://blog.logrocket.com/using-stacked-pull-requests-in-github/), so review and merging needs to happen oldest-to-newest. Thus I'll mark only this one as open for now, but in principle as soon as it's resolved the next one down the chain is also ready.

**Comment by JNmpi** [comment]
The code changes looked good to me and I have accepted them. To better test them it would be great if one could run the branch on which the pull request is based in a mybinder environment. This would make it easy to run and test the actual code without having to make a manual installation from git. Would it be possible to set up such a feature. It would tremendously speed up the reviewing process.

**Comment by liamhuber** [comment]
> To better test them it would be great if one could run the branch on which the pull request is based in a mybinder environment. This would make it easy to run and test the actual code without having to make a manual installation from git. Would it be possible to set up such a feature. It would tremendously speed up the reviewing process.

@JNmpi, in a later PR I started introducing some unit tests, but especially for aspects like UX and how usage "feels" I 100% agree it's good to just use it in review. @jan-janssen, if you already have insight on running branch-specific mybinder instances I'd be happy to hear from you. Otherwise I imagine it should be possible somehow and I'll look into it after the teaching tutorial next week.

**Pull request merged**
